### ISSUE TITLE
想问一下用u盘引导安装不知道为什么卡在第一步

### ISSUE THREAD

**Issue by DHUer** [tctien342/Dell-Inspiron-7591-Hackintosh#1]
我的也是戴尔灵越7591非顶配版本，但是我参考了这篇（https://www.sqlsec.com/2018/08/clover.html），连u盘做启动盘的时候都不能识别，真心想问问宁参考了那些资料啊。

**Comment by liuziyuan15** [comment]
去黑果小兵的blog下载最新镜像，使用etcher写入U盘，然后关闭安全启动模式，硬盘模式更改为ahci，去启动项删除windows boot manager，但不要保存。重启后即可识别。

**Comment by liuziyuan15** [comment]
When the pc wake up, the internal monitor is black，but external monitor can work. How to fix it？

**Comment by xiaobaileshi** [comment]
启动项需要自己手动在BIOS里添加
