### ISSUE TITLE
Extensions folder.

### ISSUE THREAD

**Issue by TheCakeGit** [tctien342/Dell-Inspiron-7591-Hackintosh#10]
Hi

Nice guide.

I have the same laptop and have built a hackintosh running latest Catalina, however it's a bit of a mess and I can't get the touchpad working.

Regardless I want to start again (sort of), but I won't reinstall, rather I want to replace my EFI folder with yours (I'll need to hack the config.plist of course) and clean up the /library/extensions folder. 

I have a request. Could you please drop to terminal, go the /library/extensions, type: ls -l , and paste your contents here? I need to clean up my extensions folder and would like to compare it with yours. Thx !

**Comment by tctien342** [comment]
This is my output, next ver will replace clover with opencore, currently im using it! Pretty stable and work like a charm
```sh
drwxr-xr-x  3 root  wheel  96 Apr 16  2019 ACS6x.kext
drwxr-xr-x  3 root  wheel  96 May  9  2018 ATTOCelerityFC8.kext
drwxr-xr-x  3 root  wheel  96 May  7  2018 ATTOExpressSASHBA2.kext
drwxr-xr-x  3 root  wheel  96 May  7  2018 ATTOExpressSASRAID2.kext
drwxr-xr-x  3 root  wheel  96 Sep  6  2017 ArcMSR.kext
drwxr-xr-x  3 root  wheel  96 Sep  1  2013 CalDigitHDProDrv.kext
drwxr-xr-x  3 root  wheel  96 Dec 13 05:59 EnergyDriver.kext
drwxr-xr-x  3 root  wheel  96 May  4  2018 HighPointIOP.kext
drwxr-xr-x  3 root  wheel  96 Dec  5  2017 HighPointRR.kext
drwxr-xr-x  3 root  wheel  96 Mar 31  2017 PromiseSTEX.kext
drwxr-xr-x  3 root  wheel  96 Apr 25  2018 SoftRAID.kext
```

**Comment by TheCakeGit** [comment]
Thankyou!

**Comment by TheCakeGit** [comment]
Reopening.

My extension folder is different, wondering why you need the extra files?
I've got extra files too, so I'm reviewing.

Thanks
```

drwxr-xr-x  3 root  wheel  96 16 Apr  2019 ACS6x.kext
drwxr-xr-x  3 root  wheel  96  8 May  2018 ATTOCelerityFC8.kext
drwxr-xr-x  3 root  wheel  96  7 May  2018 ATTOExpressSASHBA2.kext
drwxr-xr-x  3 root  wheel  96  7 May  2018 ATTOExpressSASRAID2.kext
drwxr-xr-x  3 root  wheel  96 15 Nov 05:40 AppleRTL815XEthernet110.kext
drwxr-xr-x  3 root  wheel  96 19 Aug 04:33 ArcMSR.kext
drwxr-xr-x  3 root  wheel  96  1 Sep  2013 CalDigitHDProDrv.kext
drwxr-xr-x  3 root  wheel  96  3 May  2018 HighPointIOP.kext
drwxr-xr-x  3 root  wheel  96 18 Jan  2017 NullCPUPowerManagement.kext
drwxr-xr-x  3 root  wheel  96 26 Jul  2019 PromiseSTEX.kext
```

**Comment by TheCakeGit** [comment]
OK I've checked another Catalina install on a completely different machine and now I've adjusted my extensions folder to be exactly the same as yours, with the exception of EnergyDriver.kext. I am not sure if it's required at least in this folder. More research needed, certainly booting OK.
