### ISSUE TITLE
Black screen - Lid set OK in BIOS

### ISSUE THREAD

**Issue by TheCakeGit** [tctien342/Dell-Inspiron-7591-Hackintosh#11]
Unfortunately I can't boot off USB stick (can't even run installer). I only get as far as Clover boot. Used the vanilla from here:
https://olarila.com/forum/viewtopic.php?f=50&t=8685

I used your Clover EFI folders and also tried theirs.

BIOS is set OK. Have turned off power up when using the lid.

My laptop is perhaps slightly different (10th gen comet lake, Intel MX250):
https://www.dell.com/en-us/work/shop/tablets-and-2-in-1-laptops/new-inspiron-15-7591-2-in-1-laptop/spd/inspiron-15-7591-2-in-1-laptop/cai1572n1w10p2c05b

Black screen every time.

Strangely I have managed to get it working before using a different method on the same laptop, I broke it and started again (and I'm very annoyed with myself about not backing up and forgetting what I did).

Oh well!

Just wondering if you may have any thoughts... apprecaited.

**Comment by TheCakeGit** [comment]
Spoke too soon!
I have no idea why this works.
Deleted all ATPIO memory fixes (yes was trying/running each one... one at a time so no conflicts), and also LILU and whatevergreen from EFI. Old install boots!

Now I can look at your install...!

**Comment by TheCakeGit** [comment]
OK , my issue is whatever APTIO memory fixes I install it won't boot (think I tried them all one at a time). So I need to get NVRAM working some another way.

Whatevergreen and LILU were out of date kexts - now sorted - but I can also boot without them!

**Comment by tctien342** [comment]
> OK , my issue is whatever APTIO memory fixes I install it won't boot (think I tried them all one at a time). So I need to get NVRAM working some another way.
> 
> Whatevergreen and LILU were out of date kexts - now sorted - but I can also boot without them!

Wow, happy to your when found it fixed, next version will move to opencore <3, wait for it!

**Comment by tctien342** [comment]
Released opencore version !

**Comment by TheCakeGit** [comment]
Cool!
