### ISSUE TITLE
The last opencore cannot be used

### ISSUE THREAD

**Issue by Saopanda** [tctien342/Dell-Inspiron-7591-Hackintosh#12]
stop in "previous shutdown cause 5"

Error like "DSM" ?
Try add SSDT-LPC.aml       ..  not work     the same error

Update BIOS to 1.5.1  
Still like that

![微信图片_20200127193809](https://user-images.githubusercontent.com/33977628/73171811-9745d200-413c-11ea-924b-d74e2898b58e.jpg)

**Comment by Saopanda** [comment]
10.15.2

**Comment by tctien342** [comment]
Found It! Test this EFI and report to me <3
[EFI-OCFIX-Catalina.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4118074/EFI-OCFIX-Catalina.zip)

**Comment by tctien342** [comment]
Found it, problem in ECDV! Will release soon!
> Comfirmed worked in catalina after fix

**Comment by tctien342** [comment]
Fixed in new Release, check it
