### ISSUE TITLE
still has black screen after i closed auto power up in bios

### ISSUE THREAD

**Issue by whdycdq** [tctien342/Dell-Inspiron-7591-Hackintosh#13]
macos version:macOS Catalina 10.15.3(19D76)
i closed auto power up in bios,but it still has a black screen when i open my lid after sleep or just close lid!
to be exact,it just gray screen,because i can saw the bright changed after i pressed fn+f6 and f7,system works normally
i wonder know how to fix it
thank you!

**Comment by tctien342** [comment]
> macos version:macOS Catalina 10.15.3(19D76)
> i closed auto power up in bios,but it still has a black screen when i open my lid after sleep or just close lid!
> to be exact,it just gray screen,because i can saw the bright changed after i pressed fn+f6 and f7,system works normally
> i wonder know how to fix it
> thank you!

Oh, it should fixed when disabled power on lid in bios, i will upload new version soon then try it again

**Comment by tctien342** [comment]
@whdycdq please test it again in [v3](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/releases/tag/opencore-v3)

**Comment by whdycdq** [comment]
> @whdycdq please test it again in [v3](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/releases/tag/opencore-v3)

**Comment by whdycdq** [comment]
![QQ20200204-180851](https://user-images.githubusercontent.com/47425055/73735200-dba72280-4779-11ea-97cb-b846ebd82e4f.png)
![QQ20200204-181023](https://user-images.githubusercontent.com/47425055/73735213-df3aa980-4779-11ea-8318-53ada78c495c.png)
thank you very much!!! I've solve it,and when I use headphone ,mic worked after I select headset ,or it worked originally?
 @tctien342

**Comment by tctien342** [comment]
> ![QQ20200204-180851](https://user-images.githubusercontent.com/47425055/73735200-dba72280-4779-11ea-97cb-b846ebd82e4f.png)
> ![QQ20200204-181023](https://user-images.githubusercontent.com/47425055/73735213-df3aa980-4779-11ea-8318-53ada78c495c.png)
> thank you very much!!! I've solve it,and when I use headphone ,mic worked after I select headset ,or it worked originally?
> @tctien342

Only work after select headset!

**Comment by whdycdq** [comment]
> > ![QQ20200204-180851](https://user-images.githubusercontent.com/47425055/73735200-dba72280-4779-11ea-97cb-b846ebd82e4f.png)
> > ![QQ20200204-181023](https://user-images.githubusercontent.com/47425055/73735213-df3aa980-4779-11ea-8318-53ada78c495c.png)
> > thank you very much!!! I've solve it,and when I use headphone ,mic worked after I select headset ,or it worked originally?
> > @tctien342
> 
> Only work after select headset!

yes, and if I didn't use headphone, it also didn't work
