### ISSUE TITLE
ACPI feature request.

### ISSUE THREAD

**Issue by TheCakeGit** [tctien342/Dell-Inspiron-7591-Hackintosh#15]
I have a big ask, I was wondering if you could expand the comments for each patch so I know what the behaviour is of each. E.g. "turn off trackpad". Here:

https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/tree/master/EFI/OC/ACPI

I'm trying to do my own patches on a 10th gen "2 in 1" Inspiron, and it would very much act as a useful pointer to me. I've managed to disable the Nvidia card withnmy own patch and now I'm trying to get the trackpad to work (for instance). If I could disassemble what you've disassembled that would be great, knowing what each ones actually does would be a life saver.

Many thanks!

**Comment by tctien342** [comment]
@TheCakeGit take an shoot here: https://github.com/jsassu20/OpenCore-HotPatching-Guide
it have dell hotpatch too! good luck bro.
