### ISSUE TITLE
About Audio Problems

### ISSUE THREAD

**Issue by Shiyang-Wang** [tctien342/Dell-Inspiron-7591-Hackintosh#17]
I hava  dell 7588 and dell precision 5510，and I encountered the same problem as you about Audio that is when sometimes I start or restart my Hackintosh in both of my computers，the audio was not able to use.Did you fixed this problem?

**Comment by tctien342** [comment]
Nah, this is bug of appleALC, need wait for them to fix this
You can read research it here: https://github.com/acidanthera/bugtracker/issues/422

Right now we can only make it boot slower so kext can work correctly!

**Comment by lvs1974** [comment]
Please try this attached version (it won't work with VerbStub since this version built from acidanther master branch).
[AppleALC-1.4.7-DEBUG.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4277179/AppleALC-1.4.7-DEBUG.zip)

**Comment by Shiyang-Wang** [comment]
thank you very much，this version of applealc really work




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lvs1974"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月3日(星期二) 凌晨2:17
收件人:&nbsp;"tctien342/Dell-Inspiron-7591-Hackintosh"<Dell-Inspiron-7591-Hackintosh@noreply.github.com&gt;;
抄送:&nbsp;"来者可追"<754806081@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tctien342/Dell-Inspiron-7591-Hackintosh] About Audio Problems (#17)




Please try this attached version (it won't work with VerbStub since this version built from acidanther master branch).
 AppleALC-1.4.7-DEBUG.zip

**Comment by lvs1974** [comment]
@Shiyang-Wang: great! this fix is merged into acidanthera/AppleALC master branch and will be available in the next release (in April).
But release version has configurable delay value (0 by default).
You can specify **alcdelay**=500 in boot-args, or add **alc-delay** (type=Number) into respective DeviceProperties value.
