### ISSUE TITLE
Windows10 Blue Screen

### ISSUE THREAD

**Issue by ghost** [tctien342/Dell-Inspiron-7591-Hackintosh#19]
when i enter windows10 from OC Boot, Blue screen appears, did you meet it?

**Comment by ghost** [comment]
oh, it's ok after closing hyper-v. LOL

**Comment by yanwuu** [comment]
> oh, it's ok after closing hyper-v. LOL

     


closing hyper-v is still blue screen, probably a bitlocker problem

**Comment by tctien342** [comment]
lol, wait for me to update new version of tweaked opencore, only inject SSDT,SMBIOS on macos so win10 will fine

**Comment by ghost** [comment]
another, can i swtich macos default in OC Boot Menu when i open?

**Comment by ghost** [comment]
my pc is dell 7950，i is appear this after SMBIOS I select the macbookpro15,3
![image](https://user-images.githubusercontent.com/22871086/75123885-624e8000-56e6-11ea-8e7c-f54eb4518f19.png)
