### ISSUE TITLE
trackpad not working 

### ISSUE THREAD

**Issue by smashell** [tctien342/Dell-Inspiron-7591-Hackintosh#21]
Great job.
I've installed Mojave with clover using defalut EFI, then replace system EFI with this shipped EFI. But trackpad is not working. I install VoodooI2C.kext and VoodooI2CHID.kext with Kext Utility, still not working. 
Thanks.

**Comment by lvs1974** [comment]
I have the same issue: VoodooI2C.kext and VoodooI2CHID.kext are definitely loaded in Mojave, but trackpad does not work. But it works in Catalina.

**Comment by tctien342** [comment]
@smashell maybe mine kext is built for catalina, you can try to download from here https://github.com/alexandred/VoodooI2C/releases and replace it

**Comment by smashell** [comment]
@tctien342 Yes, It's working now, thx.
