### ISSUE TITLE
UHD630 problem

### ISSUE THREAD

**Issue by leeray-xie** [tctien342/Dell-Inspiron-7591-Hackintosh#22]
我把网卡换成了dw1560，装好黑苹果后这时关于本机可以正确识别出uhd630,然后按照指导更改了config.plist，重启之后在关于本机里显卡识别从uhd630变成了0x.

I replaced the wifi card to dw1560 and I follow the WIFI Replacement to set the config.plist. I reboot the computer. And then i found uhd630 cannot be recognized. It's identified as "0x" 。
![截屏2020-02-26下午1 40 04](https://user-images.githubusercontent.com/5785224/75315446-bf406680-589d-11ea-9335-46220e044d8e.png)

**Comment by tctien342** [comment]
@miuismart send me your config

**Comment by leeray-xie** [comment]
> @miuismart send me your config


[config.plist.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4254761/config.plist.zip)

**Comment by tctien342** [comment]
@miuismart fixed config
[config.plist.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4254796/config.plist.zip)

**Comment by leeray-xie** [comment]
@tctien342 Thanks. lt works!
