### ISSUE TITLE
Latest EFI can't boot for 10.14.6

### ISSUE THREAD

**Issue by smashell** [tctien342/Dell-Inspiron-7591-Hackintosh#23]
I use your old EFI, but it has problem of  black screen after sleep, So I download  new EFI today, But it stuck at Apple logo. MacOS is Mojave 10.14.6, dell inspiron 7590. pls help.

**Comment by tctien342** [comment]
Try this EFI, HDMI with audio will work normal after sleep:
[https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4281029/EFI.zip](url)
