### ISSUE TITLE
black screen 

### ISSUE THREAD

**Issue by smashell** [tctien342/Dell-Inspiron-7591-Hackintosh#24]
macos version: Mojave 10.14.6
EFI version: Dell-Inspiron-7591-Hackintosh-opencore-v4
Auto power up is closed in bios, but it still has a black screen after sleep and can't be waked up !
pls help.
thank you!

**Comment by tctien342** [comment]
![image](https://user-images.githubusercontent.com/26409306/75523449-a7541880-5a3e-11ea-88d2-258a84bc110b.png)
done this yet?

**Comment by smashell** [comment]
@tctien342 my bios as follows, is it right:
![bios](https://user-images.githubusercontent.com/14961633/75604550-cc1abf80-5b14-11ea-9d17-e30eed2e36aa.png)

**Comment by ghost** [comment]
I had the same problem in 10.15.3
EFI Version: v4

**Comment by ghost** [comment]
I tried V3 just now,  It's ok.

**Comment by smashell** [comment]
@DonRain Yes， V3 is ok for me too, thx.

**Comment by tctien342** [comment]
[EFI.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4270307/EFI.zip)
Pls test this and report to me, this my current built

**Comment by ghost** [comment]
no   i try to sleep, the screen is black and i can't wake it up

**Comment by smashell** [comment]
@tctien342 ，No, It's not work, still black screen.

**Comment by tctien342** [comment]
@DonRain @tctien342 mine is sleep well
Will try to find the solution

**Comment by tctien342** [comment]
[Archive.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4271880/Archive.zip)
@smashell @DonRain , hi guys!
Please test this

**Comment by ghost** [comment]
@tctien342 
No. It's not work
May be it's a problem with the notebook model.  Mine is a 97wh battery

**Comment by smashell** [comment]
@tctien342 ， It's not work.   System specification:
![hardware](https://user-images.githubusercontent.com/14961633/75647077-bb8a5680-5c86-11ea-80be-2bb689a71fad.png)

**Comment by ghost** [comment]
This is the log file I just tried to generate from my notebook sleep. It doesn't look abnormal

[log.txt](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4281321/log.txt)

**Comment by tctien342** [comment]
@DonRain try this new port: [https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4281029/EFI.zip](url)

**Comment by ghost** [comment]
@tctien342  It's OK, thanks!

**Comment by smashell** [comment]
@tctien342 It's OK now, thanks!

**Comment by yanwuu** [comment]
My laptop is a Dell 7590 (4k Sharp 97wh), a black screen will occasionally appear during use, and it is normal after waking from sleep.
