### ISSUE TITLE
Install Step

### ISSUE THREAD

**Issue by ghost** [tctien342/Dell-Inspiron-7591-Hackintosh#26]
![image](https://user-images.githubusercontent.com/22871086/75608967-67c12580-5b3f-11ea-81ca-22ae0f58c8d8.png)
What does it mean

**Comment by tctien342** [comment]
@0ytian take a look of this: https://osxlatitude.com/forums/topic/11322-broadcom-bcm4350-cards-under-high-sierramojavecatalina/
That CN-0V.. is mine DW1820a version

**Comment by ghost** [comment]
@tctien342 I have an another problem, my Bluetooth cannot connect my Bluetooth Speaker but it can list my bluetooth devices normally.
