### ISSUE TITLE
Bluetooth Problem

### ISSUE THREAD

**Issue by ghost** [tctien342/Dell-Inspiron-7591-Hackintosh#27]
This is my config.list, my bluethooth is not working now that my windows10‘s bluetooth is also not working because i cann't drive it.

[config.plist.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4279028/config.plist.zip)

**Comment by yanwuu** [comment]
> This is my config.list, my bluethooth is not working now that my windows10‘s bluetooth is also not working because i cann't drive it.
> 
> [config.plist.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4279028/config.plist.zip)

If you are using the ac9560, please disable the bcm driver. If you use a bcm network card, please disable the intel bluetooth driver.
![image](https://user-images.githubusercontent.com/17713852/75784906-e1eee580-5d9d-11ea-9177-47487640c866.png)

**Comment by ghost** [comment]
@yanwuu but why not working in my win10

**Comment by tctien342** [comment]
@yanwuu DW1820a ? Install this then go to device manager and update it
[DW1820A_Bluetooth_Win10_12.0.1.1105_USB_x86-x64_Installer_setup_ZPE.exe.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4282515/DW1820A_Bluetooth_Win10_12.0.1.1105_USB_x86-x64_Installer_setup_ZPE.exe.zip)

**Comment by ghost** [comment]
@tctien342 thanks, I will try it
