### ISSUE TITLE
dell lns 7590(Sharp 4k) for TestingBuild-050320 feedback

### ISSUE THREAD

**Issue by yanwuu** [tctien342/Dell-Inspiron-7591-Hackintosh#29]
If  Sharp 4k screen models use TestingBuild-050320 to boot system
1. Need to delete "AAPL, ig-platform-id"
2.change dpcd-max-link-rate 14000000

       

If "iAAPL, ig-platform-id" is not deleted and dpcd-max-link-rate is 0A, the screen cannot be displayed normally after wake up (similar to splitting into two screens)
If "iAAPL, ig-platform-id" is not deleted and dpcd-max-link-rate is 14, the screen will turn black.

**Comment by yanwuu** [comment]
![image](https://user-images.githubusercontent.com/17713852/76089667-0f819c00-5ff5-11ea-9919-2259e0ebd442.png)
I changed the "AAPL, ig-platform-id" value to "0900A53E" and "dpcd-max-link-rate" set to "14000000", which can boot macOS normally. I think dell lns 7590 (Sharp 4k) should be set to "0x3EA50009". Maybe all 7590 series can be set to 0x3EA50009 (default).
[https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md](url)    

![image](https://user-images.githubusercontent.com/17713852/76090144-004f1e00-5ff6-11ea-86b1-24d2fc0e1be2.png)
@tctien342

**Comment by tctien342** [comment]
@yanwuu will add to newest build when release, thank you
