### ISSUE TITLE
Dell-Inspiron-7590 fail to do

### ISSUE THREAD

**Issue by wraptor** [tctien342/Dell-Inspiron-7591-Hackintosh#3]
cpu：i7-9750H
GPU0：UHD630
GPU1：GTX 1650

the installation interface is very stuck，and restart after installation stuck in progress bar

**Comment by tctien342** [comment]
@xmhhs go here 
https://github.com/Skimige/Inspiron-759x-Hackintosh/blob/master/README.md

**Comment by wraptor** [comment]
thank you,i got it from https://github.com/LinZong/dell-inspiron-7590-hackintosh
