### ISSUE TITLE
Wi-Fi / BT with DW1820A

### ISSUE THREAD

**Issue by Juan-VC-gh** [tctien342/Dell-Inspiron-7591-Hackintosh#30]
Is the dw1820a working oob on macOS with Inspiron 7591? I was pointed to this repo because of the recently fixed bug of appleALC and reading your guide noticed the active state power management is not disabled for the dw1820a. If pin masking is needed then disabling aspm should do the trick for easier setup in case it helps.

**Comment by Juan-VC-gh** [comment]
Check my new branch on the Catalina g7 Hackintosh repo to disable aspm through device properties

**Comment by tctien342** [comment]
@Juan-VC, thank u, already have this on current build :3

**Comment by Juan-VC-gh** [comment]
There is also a different audio fix than ComboJack which I am using, it is called JackFix, you could  try it and decide which one to keep.
