### ISSUE TITLE
 OCWork fallback to windows 10 instead of linux

### ISSUE THREAD

**Issue by Mateo1234454545** [tctien342/Dell-Inspiron-7591-Hackintosh#31]
About this commit...
What are the advantages of changing it?
Does it really matter?

**Comment by tctien342** [comment]
@Mateo1234454545 just try to get better in sleep and working FN brightness key in SSDT-OCWORK, up coming build will config into this: 
![Screen Shot 2020-03-09 at 23 49 05](https://user-images.githubusercontent.com/26409306/76237281-9c7c5d80-6260-11ea-86fc-03f99b3cecfe.png)
