### ISSUE TITLE
High cpu usage after wake (kernel_task)

### ISSUE THREAD

**Issue by lvs1974** [tctien342/Dell-Inspiron-7591-Hackintosh#32]
I noticed that after wake (and sometimes after boot) kernel_task loads cpu with 70-80%.
After I ran **sudo spindump 0 -reveal** and opened report, I figured out the culprit is AppleHDA driver, which tries to execute and apply some verbs.

I completely turned off ComboJack and disabled VerbStub kext, but it did not help.
I opened AppleALC and modified AppleALC/Resources/PinConfigs.kext/Contents/Info.plist for layout 13 (removed WakeConfigData and WakeVerbReinit). Built AppleALC and reboot.

I did not observe high cpu usage any more, but:
1. no sound after wake
2. headset microphone does not work (no switching with ComboJack & VerbStub loaded)

I changed layout to 77:
1. there is a sound after wake
2. headset microphone does not work

It seems that layout 13 was created specially for Dell 7570 by DalianSky, but it causes these troubles on Inspiron 7590 (@tctien342: could you check on 7591, please?).
This high cpu usage lasts for 3-5 minutes (sometimes even longer), and this might take a lot of juice from battery.

**Comment by tctien342** [comment]
@lvs1974 test 3 times but not facing with that in 7591 - layout 13, will revert to layout 77 if you want.
Mine after wake will up to 50% percent of cpu but just 6 - 7 second will back to normal

**Comment by lvs1974** [comment]
@tctien342, reverting is not necessary, please leave it as is.
Could you try the following:

1. Unplug your laptop from power source
2. Close lid.
3. Wait for 5-6 hours.
4. Open lid - keyboard backlight is turned on
5. Press any key - display backlight is turned on
6. Check CPU usage for kernel task

BTW: Don't you know why display backlight is not turned on automatically if I open lid?
It worked in previous version - **7***.

**Comment by tctien342** [comment]
@lvs1974 it wake by lid, but not quick, it take me about 8 to 10 seccond to wake. All tested before is on battery. I will test again tonight and report on tomorrow

**Comment by lvs1974** [comment]
@tctien342, thank you!

**Comment by lvs1974** [comment]
> @lvs1974 it wake by lid, but not quick, it take me about 8 to 10 seccond to wake. All tested before is on battery. I will test again tonight and report on tomorrow

Mine laptop does not turn on display backlight even in 1 minute.
I have to press any key.
Did you turn on that option "Turn on power by LID" in BIOS,
or you only use lidwake in pmset?

**Comment by tctien342** [comment]
"Turn on power by LID" this feature to turn on power while laptop is power off, i turned it off as it can cause darkscreen when wake

Mine pmset conf:
```
Currently in use:
 lidwake              1
 autopoweroff         0
 standbydelayhigh     86400
 autopoweroffdelay    28800
 proximitywake        0
 standby              0
 standbydelaylow      10800
 ttyskeepawake        1
 hibernatemode        0
 powernap             0
 highstandbythreshold 50
 hibernatefile        /var/vm/sleepimage
 displaysleep         10
 womp                 0
 networkoversleep     0
 sleep                1 (sleep prevented by sharingd, coreaudiod)
 tcpkeepalive         0
 halfdim              1
 acwake               0
 disksleep            10
```

**Comment by lvs1974** [comment]
Here are mine settings:

> Currently in use:
 standbydelaylow      3600
 standby              1
 halfdim              1
 hibernatefile        /var/vm/sleepimage
 proximitywake        1
 powernap             1
 disksleep            0
 standbydelayhigh     4600
 sleep                1 (sleep prevented by AddressBookSourceSync)
 autopoweroffdelay    28800
 hibernatemode        3
 autopoweroff         1
 ttyskeepawake        1
 displaysleep         13
 tcpkeepalive         1
 highstandbythreshold 50
 acwake               0
 lidwake              1

But display backlight isn't turned on after opening lid or pressing key.
I always have to press key one more time.

**Comment by lvs1974** [comment]
@tctien342, I turned on option "Turn on power by LID" in BIOS, and now display backlight is turned on immediately when I open lid!
But it has no influence on regular sleep (with open lid). Still have to press key, wait until keyboard backlight is turned on, then press key one more. Only then display backlight is turned on.

**Comment by tctien342** [comment]
@lvs1974 can you try `sudo pmset -a hibernatemode 0` and report ?

**Comment by lvs1974** [comment]
> @lvs1974 can you try `sudo pmset -a hibernatemode 0` and report ?

I set hibernatemode to 0, reboot and disabled bios option "Turn on power by LID". Boot into macos, unplug power source. I have a USB cable with power indicator, so I use this cable to detect a moment when power was gone from USB port. So, I close Lid an wait until usb port left without power. Then I open Lid again. USB power comes back immediately, 2 seconds later keyboard backlight is turned on. After 7-10 seconds keyboard backlight is is turned off, and usb port left without power again.

**Comment by lvs1974** [comment]
Finally, I have managed to get similar behaviour as in version 7*:

1. Remove from SSDT-DGPU.aml method _WAK
2. Put these tables from version 7* into APCI: SSDT-EXT4-WakeScreen.aml, SSDT-PTSWAK.aml
3. Add these tables into config.plist
4. Add apci binary patch "PTSWAK: Rename method _PTS to ZPTS and use with SSDT-PTSWAK.aml to fix dGPU power sapping", but this may be optional.

So, the main magic is performed in SSDT-EXT4-WakeScreen.aml, method EXT4.

**Comment by lvs1974** [comment]
So, I just added call of external method Ext4 in method _WAK into SSDT-DGPU:
[SSDT-DGPU.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4313200/SSDT-DGPU.zip)
[SSDT-EXT4-WakeScreen.aml.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4313202/SSDT-EXT4-WakeScreen.aml.zip)

**Comment by tctien342** [comment]
oh, it a bit strange, mine is work well without that patch, tested sleep at night without plugin then wake again after 10 hour:
+ Battery loss 8%
+ Wake normal after lid, no need to press any key
+ No high kernel_task, quickly checked but it only 10% of cpu

Mine is on macos 10.15.2

**Comment by lvs1974** [comment]
@tctien342, mine is on 10.15.3 - the latest release version.
Could you include these fixes into your repository, please?

**Comment by tctien342** [comment]
@lvs1974 okay, i'll add it to repo

**Comment by Saopanda** [comment]
The computer continued to use for 5 hours without sleeping. Suddenly it feels very hot and I find that the kernel_task load is between 60 and 70.
May last for an hour or more.

After I found it hot, I tried to sleep and wake it up, and kernel_task returned to normal load 7 to 8

Please bear with me computer translation
10.15.2

**Comment by lvs1974** [comment]
Unfortunately this layout 13 causes many issues.

1. Sometimes, after boot I see that input is switched to Line-In, but nothing was plugged into headphone socket.
2. If I plug my headset in, it usually works for the first time, but sometimes input is not switched from internal microphone to external microphone.
3. If i plug/unplug headset a few times, I see a strange noise in headphones, and kernel_task occupies CPU for 50-70%.

Below spindump log:
[apple_hda_spindump.txt](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4317471/apple_hda_spindump.txt)

**Comment by tctien342** [comment]
@lvs1974 can you test this with layout 77?
[AppleALC.kext.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4318215/AppleALC.kext.zip)

**Comment by lvs1974** [comment]
@tctien342, yes I can, thank you!

**Comment by lvs1974** [comment]
@tctien342, I tested attached AppleALC with layout 77.
After boot in Preferences pane "Sound" - Input I see "Line in - Audio line-in port".
Input level is always jumping, nothing is plugged into headphone socket.
When I plug headset or headphones - Internal Speakers are changed to Headphones, Line in stays without any changes.
I made a test call in Skype, and I could hear only noise.

But from CPU usage perspective it is OK!

**Comment by tctien342** [comment]
@lvs1974 the linein volume is higher than normal, you can set it into 60% is enough

**Comment by lvs1974** [comment]
I decided to repeat test:
I shutdown laptop, unplugged power source.
Turned it on and boot.
After boot in Preferences pane "Sound" - Input I see "Line in - Audio line-in port".
But Input level did not jump, it was at 0.
I plugged in my headset and saw that input level corresponds to the sound near to microphone.
I made a Skype test call and everything is great!

**Comment by lvs1974** [comment]
Anyway - this AppleALC with layout 77 is much much better than original kext with layout 13!
And CPU usage is OK!
This is completely stable solution!
Thank you!

**Comment by lvs1974** [comment]
Regarding internal microphone (Digital Microphone Array):
https://forum.manjaro.org/t/inspiron-7590-integrated-microphone-not-detected/123897/29
This is the first linux, where it works (I checked - it really works).
But I am afraid it will be extremely hard to adapt drivers/kernel fixes from linux to MacOS. It is about [sof-firmware](https://github.com/thesofproject/sof), and DMICS - it is actually DSP, so there is firmware, and this firmware binded to the linux kernel.
 
If would Apple have used these DMICS in their MacBooks, they would added support for them into AppleHDA. May be in the future...

**Comment by tctien342** [comment]
@lvs1974 ya, i have hear about SOF before, hope apple will support it in feature
