### ISSUE TITLE
update.py errors

### ISSUE THREAD

**Issue by Jeff406** [tctien342/Dell-Inspiron-7591-Hackintosh#35]
Hi anh,
Please have a look
![Screen Shot 2020-03-11 at 12 17 17 PM](https://user-images.githubusercontent.com/6175321/76385301-03e6fa00-6394-11ea-8397-6a7fd70b36fc.png)
BTW, please give more instruction how the update.py works, as I know you centralized all the fixes into one tool (maybe it creates the EFI folder afterward?) . For example, in your installation guide:

_Replace EFI folder in USB EFI partition with this shipped EFI folder_
=> Where to get the EFI folder because you've removed it

_After install success, run PostInstall/install.sh in terminal_
=> no install.sh in PostInstall because it's in Combojackfix
...

Many thanks,
Thai

**Comment by tctien342** [comment]
change `python` to `python3` then test again, need more time to edit Readme.md, sorry u for about this

**Comment by Jeff406** [comment]
Thank you anh for great tools!
