### ISSUE TITLE
Some problems I met

### ISSUE THREAD

**Issue by MengfeiSun95** [tctien342/Dell-Inspiron-7591-Hackintosh#36]
Thanks for your EFI, I installed mac os successfully.
My laptop is Dell Inspiron 7590 (cpu:i7-9750H，1080P)
During my installation, I found some problems:
1. My installation GUI language is Russia, maybe because of the clover option;
2. I replaced DW1820A(CN-08PKF4), if your laptop is same as mine, you should shield the pin, like this https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html#group-15;
3. This EFI also supports Mac OS 10.15.3.

Hope my experience could help others who are rookies like me.
Thank you again！

**Comment by MengfeiSun95** [comment]
And another problem is sleep. 
When I close the lid of the laptop, then open it, my screen is flashing.
I want to know the reason.

**Comment by lvs1974** [comment]
@MengfeiSun95, could check one thing related to Wi-Fi and DW1820a, please?
Can you turn Wi-Fi off via Wi-Fi icon in status bar, then put your laptop to sleep, wake it and turn Wi-Fi on? Will it work properly?
