### ISSUE TITLE
Traceback update.py --build

### ISSUE THREAD

**Issue by magonzalez112** [tctien342/Dell-Inspiron-7591-Hackintosh#38]
I created a personal token so I can use the script (I censored and changed it to random characters to post it here)
Here is the traceback I get, if I say n and Y to update packages for CLOVER, it fails patching now I understand why my trackpad doesn't work it wasn't patched LOL. 
I'm trying to fix it myself, but I don't know how long will it take. For now I'm using a mouse

```
miguel@HackBook [17:53:26] [~/Projects/Dell-Inspiron-7591-Hackintosh] [master *]
-> % python3 update.py --build
Enter your github read access token: 811e40dd13fh19b2f8ad5@@@@@@@@@@3c62f3d3a
:: Updating SSDTs
/Users/miguel/Projects/Dell-Inspiron-7591-Hackintosh/CLOVER patches updated
/Users/miguel/Projects/Dell-Inspiron-7591-Hackintosh/OC patches updated
==> Do packages update for CLOVER?(Y/n)n
:: Set delay after typing to 50ms
Traceback (most recent call last):
  File "update.py", line 813, in <module>
    default(folders)
  File "update.py", line 760, in default
    patching(folder / mapper.get('Kexts', 'Kexts'))
  File "update.py", line 494, in patching
    info = Plist(kexts / 'VoodooI2CHID.kext' / 'Contents' / 'Info.plist')
  File "update.py", line 214, in __init__
    with open(file, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/miguel/Projects/Dell-Inspiron-7591-Hackintosh/CLOVER/kexts/Other/VoodooI2CHID.kext/Contents/Info.plist'
```
```
miguel@HackBook [18:08:19] [~/Projects/Dell-Inspiron-7591-Hackintosh] [master *]
-> % python3 update.py --build
Enter your github read access token: 811e40dd84fj19b2f8dd5@@@@@@@@@@3d64f3d3d
:: Updating SSDTs
/Users/miguel/Projects/Dell-Inspiron-7591-Hackintosh/CLOVER patches updated
/Users/miguel/Projects/Dell-Inspiron-7591-Hackintosh/OC patches updated
==> Do packages update for CLOVER?(Y/n)Y
:: Checking updates...
https://api.github.com/repos/acidanthera/AirportBrcmFixup/releases/latest
https://api.github.com/repos/tctien342/Dell-Inspiron-7591-Hackintosh/releases/tags/110320
Traceback (most recent call last):
  File "update.py", line 813, in <module>
    default(folders)
  File "update.py", line 758, in default
    update_packages(packages)
  File "update.py", line 450, in update_packages
    if package.check_update():
  File "update.py", line 320, in check_update
    info = json.loads(urlopen(req).read())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Model 7590, 9750H 32gb RAM, 54Wh battery, 1080p display

**Comment by magonzalez112** [comment]
Fixed...
Look at this line the path:
`FileNotFoundError: [Errno 2] No such file or directory: '/Users/miguel/Projects/Dell-Inspiron-7591-Hackintosh/CLOVER/kexts/Other/VoodooI2CHID.kext/Contents/Info.plist'`

**Projects/Dell-Inspiron-7591-Hackintosh/CLOVER/kexts/Other/VoodooI2CHID.kext/**
Originally kexts on the project are on this route:
Projects/Dell-Inspiron-7591-Hackintosh/kexts/

**SOLUTION**:
Put in the clover path of the project kexts/other all the kexts... Then you're good to go
If I say yes, I get the same error, saying no to update clover and opencore  packages, the script finishes execution well

**Comment by magonzalez112** [comment]
The trackpad still not working I can't understand.

**Comment by magonzalez112** [comment]
Got trackpad working back using old kexts from here:
https://www.tonymacx86.com/threads/nearly-success-catalina-on-dell-inspiron-7590.285606/

**Comment by tctien342** [comment]
lol, maybe it failed to download kext, mine is built success

**Comment by ghost** [comment]
@tctien342 I think that you can take all kext  to this repo

**Comment by magonzalez112** [comment]
> @tctien342 I think that you can take all kext to this repo

I think thats a good improvement, if in any case, the script can't connect properly to gather the latest kext at least you have some old ones that work

**Comment by ghost** [comment]
@tctien342 Yeah, but it's easy to use in China

**Comment by magonzalez112** [comment]
Tried again execution, and everything fixed.  Now it downloads and patches kexts without problems, You fix it in the last commits I guess. Thank you.
I'm moving to Opencore since I have two drives. I will move Clover to the other drive and create an entry to Opencore so I still have a fancy bootloader to boot into linux, windows or mac os
