### ISSUE TITLE
high cpu power cost when wake up

### ISSUE THREAD

**Issue by OysterQAQ** [tctien342/Dell-Inspiron-7591-Hackintosh#40]
platform:dell 7590 i7 aud4k
os:15.4
efi:latest
sometime cpu power cost continued in 26w when wake up ,seem cpu frequency scaling is useless .
only restore normal power cost when i reboot it

**Comment by tctien342** [comment]
@OysterQAQ cpu power cost or total system power cost ? if due to cpu, you can try to generate an CPUFriend once by using [this](https://github.com/stevezhengshiqi/one-key-cpufriend)

**Comment by OysterQAQ** [comment]
it is cpu power cost,and CPUFriend i generated by myself also cause the high power cost.it almost 100% happen when i cover the Laptop and open it after 10s.when it happened , neither of  reboot and sleep  are useless
