### ISSUE TITLE
Can not work properly when sleeping and waking up

### ISSUE THREAD

**Issue by steven-panxd** [tctien342/Dell-Inspiron-7591-Hackintosh#43]
I went through all steps you posted here and everything can work correctly except sleeping and waking up. It can sleep and I can hear the fan stopped, but after I tried to wake it up, I can see it turned on the light of the screen but nothing displayed. Also, I believe the system is still working since I can hear the sounds when tapping some buttons. The wired thing is that it can not display anything after waking up.

**Comment by steven-panxd** [comment]
Model: 7590 1080p
Processor: I7-9750H
OS Ver.: 10.5.4

**Comment by tctien342** [comment]
@steven-panxd did your turn off power on lid function in bios ?

**Comment by steven-panxd** [comment]
@tctien342 Yes.

**Comment by tctien342** [comment]
@steven-panxd please test my current build with many optimize, will merge to OC soon
> Edit it to match your laptop config before use
[CLOVER-BETA-40420.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4431958/CLOVER-BETA-40420.zip)

**Comment by steven-panxd** [comment]
I can not use my trackpad with the new EFI.

**Comment by tctien342** [comment]
@steven-panxd , try to rebuilt kext cache or delete voodooi2c + voodooi2chid + voodooinput and use old voodooi2c + voodooi2chid
+ New kext work well in GPIO mode, more smoother and fixed many bug compare to old one

**Comment by steven-panxd** [comment]
I just checked some closed issues and I found this version works for me.
https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/tree/opencore-v3

**Comment by steven-panxd** [comment]
I found the older EFI below can work on my laptop, too.
https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4281029/EFI.zip

So, I compared all items in config.plist with the latest release and I found if I replace `DeviceProperties > Add > PciRoot(0x0)/Pci(0x2,0x0)` by its value in the older EFI, the newest one can work properly on my laptop.

It means replacing
`<dict>
	<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
	<dict>
		<key>AAPL,ig-platform-id</key>
		<data>
		CQClPg==
		</data>
		<key>AAPL,slot-name</key>
		<string>Internal@0,2,0</string>
		<key>device_type</key>
		<string>VGA compatible controller</string>
		<key>disable-external-gpu</key>
		<data>
		AQAAAA==
		</data>
		<key>dpcd-max-link-rate</key>
		<data>
		FAAAAA==
		</data>
		<key>enable-dpcd-max-link-rate-fix</key>
		<data>
		AQAAAA==
		</data>
		<key>enable-hdmi-dividers-fix</key>
		<data>
		AQAAAA==
		</data>
		<key>enable-hdmi20</key>
		<data>
		AQAAAA==
		</data>
		<key>enable-lspcon-support</key>
		<data>
		AQAAAA==
		</data>
		<key>framebuffer-con0-alldata</key>
		<data>
		AAASAAIAAACYAAAAAQUSAAAIAACHAQAAAgYSAAAIAACHAQAAAwQSAAAIAACH
		AQAA
		</data>
		<key>framebuffer-con0-enable</key>
		<data>
		AQAAAA==
		</data>
		<key>framebuffer-con3-has-lspcon</key>
		<data>
		AQAAAA==
		</data>
		<key>framebuffer-con3-preferred-lspcon-mode</key>
		<data>
		AQAAAA==
		</data>
		<key>framebuffer-patch-enable</key>
		<data>
		AQAAAA==
		</data>
		<key>framebuffer-portcount</key>
		<data>
		BAAAAA==
		</data>
		<key>framebuffer-unifiedmem</key>
		<data>
		AAAAgA==
		</data>
		<key>hda-gfx</key>
		<string>onboard-1</string>
		<key>model</key>
		<string>Intel UHD Graphics 630 (Mobile)</string>
	</dict>
</dict>`
by
`<dict>
	<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
	<dict>
		<key>AAPL,ig-platform-id</key>
		<data>
		AACbPg==
		</data>
		<key>disable-external-gpu</key>
		<data>
		AQAAAA==
		</data>
		<key>dpcd-max-link-rate</key>
		<data>
		CgAAAA==
		</data>
		<key>enable-dpcd-max-link-rate-fix</key>
		<data>
		AQAAAA==
		</data>
		<key>enable-hdmi-dividers-fix</key>
		<data>
		AQAAAA==
		</data>
		<key>enable-hdmi20</key>
		<data>
		AQAAAA==
		</data>
		<key>enable-lspcon-support</key>
		<data>
		AQAAAA==
		</data>
		<key>framebuffer-con1-alldata</key>
		<data>
		AQUJAAAEAACHAQAA
		</data>
		<key>framebuffer-con1-enable</key>
		<data>
		AQAAAA==
		</data>
		<key>framebuffer-con2-alldata</key>
		<data>
		AgYJAAAEAACHAQAA
		</data>
		<key>framebuffer-con2-enable</key>
		<data>
		AQAAAA==
		</data>
		<key>framebuffer-con3-alldata</key>
		<data>
		AwQKAAAIAACHAQAA
		</data>
		<key>framebuffer-con3-enable</key>
		<data>
		AQAAAA==
		</data>
		<key>framebuffer-con3-has-lspcon</key>
		<data>
		AQAAAA==
		</data>
		<key>framebuffer-patch-enable</key>
		<data>
		AQAAAA==
		</data>
		<key>framebuffer-portcount</key>
		<data>
		BAAAAA==
		</data>
		<key>framebuffer-unifiedmem</key>
		<data>
		AAAAgA==
		</data>
	</dict>
</dict>`

It looks like something about the graphics card but I'm not sure how it works.
