### ISSUE TITLE
Bluetooth not work. ac9560

### ISSUE THREAD

**Issue by Ericjt11** [tctien342/Dell-Inspiron-7591-Hackintosh#47]
I use CF-811AC wifi and the 7590's own bluetooth
They worked normally when I used the previous efi and oc. When I chance to the lastest oc and efi ,wifi works normally but bluetooth not work. 
And there's no intel bluetooth driver in the Kernal in the oc operation. Only the bcm driver.
When i put it in, even the computer fail to boot.
![Xnip2020-05-08_13-02-48](https://user-images.githubusercontent.com/60682946/81373258-dbc70d80-912e-11ea-8478-a558b83d02b3.jpg)

**Comment by tctien342** [comment]
@Ericjt11 closed, you can read about intel [here](https://openintelwireless.github.io)
