### ISSUE TITLE
Sleep Wake failure in EFI

### ISSUE THREAD

**Issue by lakie0605** [tctien342/Dell-Inspiron-7591-Hackintosh#48]
Use lastest release:

Sleep Wake failure in EFI

Failure code:: 0xffffffff 0x0000001f

Please IGNORE the below stackshot

================================================================
Date/Time:        2020-05-08 11:40:58 +0800
OS Version:       ??? ??? (Build ???)
Architecture:     x86_64
Report Version:   29

Data Source:      Stackshots
Shared Cache:     0x1f42000 8965EE45-FE6E-3716-95CC-9D6E1E65267D

Event:            Sleep Wake Failure
Duration:         0.00s
Steps:            1

Boot args:        agdpmod=vit9696 darkwake=1 gfxrst=1 igfxfw=2 igfxpavp=1

Time Awake Since Boot: 11s

Process:          swd [262]
Architecture:     x86_64
Footprint:        440 KB
Start time:       2020-05-08 11:40:58 +0800
End time:         2020-05-08 11:40:58 +0800
Num samples:      1 (1)

  Thread 0x6f8    1 sample (1)    priority 4 (base 4)
  <thread QoS background (requested background), thread darwinbg, process darwinbg, IO tier 2>
  1  start + 1 (libdyld.dylib + 109769) [0x7fff68eb0cc9] 1
    1  ??? [0x10368d454] 1
      1  ??? [0x10368d1dd] 1
        1  __stack_snapshot_with_config + 10 (libsystem_kernel.dylib + 135862) [0x7fff690122b6] 1
         *1  ??? [0xffffff80002c8206] 1
           *1  ??? [0xffffff80009875f7] 1
             *1  ??? [0xffffff80008a0001] 1
               *1  ??? [0xffffff80002eb9e7] (running) 1

  Binary Images:
        0x7fff68e96000 -     0x7fff68eccfff  libdyld.dylib (750.5)               <D2A07EF5-A64B-3692-BE13-89DAA2EC5E80>  /usr/lib/system/libdyld.dylib
        0x7fff68ff1000 -     0x7fff6901dfff  libsystem_kernel.dylib (6153.101.6) <E76440E1-D1E8-3D9A-8B47-D01F554FF1C4>  /usr/lib/system/libsystem_kernel.dylib
Model: MacBookPro15,3, BootROM 1037.100.358.0.0, 4 processors, Quad-Core Intel Core i5, 2.4 GHz, 16 GB, SMC 1.74f4
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Memory Module: DIMM A, 8 GB, DDR4, 2666 MHz, 802C0000802C, 8ATF1G64HZ-2G6E1
Memory Module: DIMM B, 8 GB, DDR4, 2666 MHz, 04CB000002B5, unknown
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x22), Broadcom BCM43xx 1.0 (7.21.190.33 AirPortDriverBrcm4360-1601.1)
Bluetooth: Version 7.0.4f6, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
PCI Card: Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem, Signal processing controller, Internal@0,4,0
PCI Card: Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model, System peripheral, Internal@0,8,0
PCI Card: Cannon Lake PCH Thermal Controller, Signal processing controller, Internal@0,18,0
PCI Card: Cannon Lake PCH USB 3.1 xHCI Host Controller, USB controller, Internal@0,20,0
PCI Card: Cannon Lake PCH Shared SRAM, RAM memory, Internal@0,20,2
PCI Card: Cannon Lake PCH Serial IO I2C Controller #1, sppci_unknown, Internal@0,21,1
PCI Card: Cannon Lake PCH HECI Controller, Communication controller, Internal@0,22,0
PCI Card: Cannon Lake Mobile PCH SATA AHCI Controller, SATA controller, Internal@0,23,0
PCI Card: Cannon Lake PCH SMBus Controller, SMBus, Internal@0,31,4
PCI Card: Cannon Lake PCH SPI Controller, sppci_unknown, Internal@0,31,5
PCI Card: DW1820A (BCM4350) 802.11ac Wireless, Airport Extreme, WLAN
PCI Card: pci1c5c,1327, sppci_nvme, Internal@0,29,0@60,0,0
PCI Card: pci126f,2263, sppci_nvme, Internal@0,27,4@59,0,0
PCI Card: sppci_expresscard_name, System peripheral, Internal@0,27,0/0,0/0,0/0,0
PCI Card: sppci_expresscard_name, USB controller, Internal@0,27,0/0,0/2,0/0,0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
USB Device: BCM2045A0
USB Device: Integrated_Webcam_HD
Thunderbolt Bus:

**Comment by usr-sse2** [comment]
The same on 7390 2-in-1.

**Comment by cassius425** [comment]
Which configuration are you, if it is the 1080p version, you can try to modify the following configuration with OC configurator 
_PciRoot(0x0)/Pci(0x2,0x0)_ -> _dpcd-max-link-rate_ value **14000000** to **0A000000**.

**Comment by usr-sse2** [comment]
On 7390 it happened because of lidwake being enabled in pmset. It crashed when opening the lid. Disabled lidwake and it doesn’t crash.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cassius425** [comment]
![image](https://user-images.githubusercontent.com/17983182/89725736-1baad300-da45-11ea-9826-2cd0590355f2.png)
This is the pmset of my 7590.I don't know if it's applicable to you. You can have a try.
