### ISSUE TITLE
Can't recognize usb devices

### ISSUE THREAD

**Issue by PicoHugMe** [tctien342/Dell-Inspiron-7591-Hackintosh#5]
Hi, after using your EFI, My computer can recognize my USB WIFI and PS/2 devices, including my PS/2 Mouse. But, I found my computer can't recognze my u-disk and my mobile hard disk. Do you have any advices? Even in the Disk Utility can't find my USB devices both. At terminal i use 'diskutil list' can't find anymore devices too.

**Comment by tctien342** [comment]
"mobile hard disk" ? Android MTP ? U should install this to use android MTP in mac os: https://www.android.com/filetransfer/
As u-disk maybe your usb port is different as mine, try to replace this ssdt UIAC: https://github.com/RehabMan/OS-X-USB-Inject-All/blob/master/SSDT-UIAC-ALL.dsl
