### ISSUE TITLE
Thunderbolt 3 Egpu

### ISSUE THREAD

**Issue by loisdroug27** [tctien342/Dell-Inspiron-7591-Hackintosh#51]
Hi, i have a egpu Razer Core x with rx 580 wich is working on windows 10 but not on catalina 10.15.4, i have the inspiron 7590 version with i7 and 1080p screen and with your last OC EFI. Can i try something to get it working ? Do i need to disable DGPU in bios value because it's the only thing i didnt do. Please help me get this Razer Core TB3 working it will be great. Thank you for your amazing work.

**Comment by tctien342** [comment]
@loisdroug27 i don't have egpu to test, sorry about this, u can try to patch it by yourself!
