### ISSUE TITLE
My CLOVER can‘t work the headset mic by EarPods with 3.5 mm Headphone Plug

### ISSUE THREAD

**Issue by PicoHugMe** [tctien342/Dell-Inspiron-7591-Hackintosh#52]
Hello, here I have a version of CLOVER that can work the headset mic by EarPods with 3.5 mm Headphone Plug. But that not means it can work every time. Once you boot your MacOS, you will have 50% to get a Perfect MacOS that you can use the headset mic, or you will have 50% to be failed that your headset mic will have a current sound like cicicici. 

I used it before I changed my EFI from CLOVER to OpenCore, after I changed, I can't use the headset mic anymore, even I installed the ComboJack after that.

Here is my used CLOVER, I wonder how can make it work on my OpenCore😂
Hope you can help me.
[CLOVER](https://github.com/zhaogarvie/Dell-Inspiron-7591-CLOVER-Hackintosh/raw/master/CLOVER.zip)

**Comment by lvs1974** [comment]
Hi, could you replace your existing ComboJack with the attached one and check, please?
[ComboJack.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4772328/ComboJack.zip)
I think the location is /usr/local/sbin/ComboJack.

**Comment by PicoHugMe** [comment]
> Hi, could you replace your existing ComboJack with the attached one and check, please?
> [ComboJack.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/4772328/ComboJack.zip)
> I think the location is /usr/local/sbin/ComboJack.

Thank you for your advising. I've tried your way but it seems still not work.

**Comment by Nathan-Liu-sudo** [comment]
you can see install.sh under postinstall/combojack/fix
drag it into terminal, input your password, reboot your machine

**Comment by PicoHugMe** [comment]
> you can see install.sh under postinstall/combojack/fix
> drag it into terminal, input your password, reboot your machine

Yeah, i've done what you said, but it seems have no changes. My headset mic still not work, I just can hear sounds from the headset instead of input something through the headset mic.

**Comment by Nathan-Liu-sudo** [comment]
change the config.plist
Audio：Realtek ALC295（Layout-ID = 77）

**Comment by PicoHugMe** [comment]
> change the config.plist
> Audio：Realtek ALC295（Layout-ID = 77）

Yeah i've changed my config.list, but it's still not work😅 But that's fine, i'll try another way.

**Comment by magonzalez112** [comment]
I'm having a problem related to this. After update, the window that let you choose the device doesn't appear anymore. I connect speakers or headphones and they don't work. (In Preferences>audio the device internal speakers actually changes to headphones, but no sound at all)
I tried to reinstall the post install script. but no luck, only internal speakers work. I don't know what's the problem. I'm using OpenCore btw. 
Anyone can help me or point me which should I watch to notice the problem ? 
My system is rock solid, that's the only issue I have

**Comment by lfpai** [comment]
I have the same problem。Have you solved the problem？
