### ISSUE TITLE
CombijackFix/install.sh not work

### ISSUE THREAD

**Issue by Nathan-Liu-sudo** [tctien342/Dell-Inspiron-7591-Hackintosh#54]
oc 0.58 mac os 10.15.5
it worked on clover 
i change clover to oc on last weekend，then it not work
i‘ve to run ComboJack once the machine reboot
can you help me？thankq

**Comment by magonzalez112** [comment]
Did you find a fix ? I'm running OpenCore 0.5.9
For me the daemon is running, but the window doesn't pop up when I connect something. How do I trigger the window manually at least ?

**Comment by liuziyuan15** [comment]
@magonzalez112 
Because it's turned off by default. You may change it in config.plist.

**Comment by magonzalez112** [comment]
@liuziyuan15
In opencore config.plst ??
if you refer to the VerbStub, it is enabled
<a href="https://ibb.co/L9nBC34"><img src="https://i.ibb.co/WBg7cLS/Captura-de-pantalla-2020-07-04-a-las-16-20-30.png" alt="Captura-de-pantalla-2020-07-04-a-las-16-20-30" border="0"></a>

**Comment by Nathan-Liu-sudo** [comment]
@magonzalez112 
Sorry, I gave the wrong answer. you may change it in ComboJack not config.plist. But I do not know how to do it.

**Comment by magonzalez112** [comment]
@liuziyuan15 there is nothing to do, the only files to edit are: install.sh (it only places the files in the correct path) and com.XPS.ComboJack.plist (it set up the daemon) 
the rest of them are binary files.
There is no configuration file.

**Comment by magonzalez112** [comment]
If anyone arrives here. I fixed it!!
The window still isn't showing up, but if I connect my headphones or external speakers it works.
I used combojack from here:
https://github.com/Pinming/Dell-Inspiron-7590-Hackintosh-Opencore
Thank you @pinming
I wonder why the window to select device is not showing up, but it is ok for me, it works, I don't use headset
Give it a try @liuziyuan15 if you still have problems with it

**Comment by Nathan-Liu-sudo** [comment]
@magonzalez112 
I know it works. It's just that It was my first time using MAC OS. So I thought the.sh file was run by double-clicking. When I went back to your question I thought you had to get the window out. Whatever, 3q.
