### ISSUE TITLE
 Add Internal Microphone Support

### ISSUE THREAD

**Issue by Hagird** [tctien342/Dell-Inspiron-7591-Hackintosh#61]
May I ask if the author can add microphone support, or can the idea be mentioned。

**Comment by tctien342** [comment]
This is impossible task, as our internal mic need addition drivers to handle this, at linux we have to use SOF firmware to active it! Someone can port this into macos then we can use our internal mic

**Comment by LeeBinder** [comment]
Here's how:

1. open a request at [freelancer.com](https://www.freelancer.com)
![Bildschirmfoto 2021-03-07 um 22 40 06](https://user-images.githubusercontent.com/39203497/110255881-543c6c00-7f96-11eb-87f3-f1415c120247.jpg)
![Bildschirmfoto 2021-03-07 um 22 40 43](https://user-images.githubusercontent.com/39203497/110255893-5c94a700-7f96-11eb-9fca-cf6e859f7f34.jpg)

It's crucial to word it as precise as possible, and to supply all available data from your Dell from both OSes, macOS and Linux, right away.

2. wait for bids, compare offers and devs

3. if you can't afford the most promising  offer, open a fundraiser at [GoFundMe](https://www.gofundme.com/) or alike and alert all the [Dell Inspiron 7591 Hackintosh](https://www.google.com/search?sclient=psy-ab&site=&source=hp&btnG=Search&q=Dell+Inspiron+7591+Hackintosh&oq=&gs_l=&pbx=1) crew. Or maybe by now freelancer.com even has a crowd-funding option.

It should not take longer than a couple of weeks at the most before you have a fully working audio incl. mic driver kext for macOS!
