### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by jamieernest** [tctien342/Dell-Inspiron-7591-Hackintosh#63]
Not sure how to contact you so I made an issue: Thank you very much for this repo! This inspired me to do the repo for the sucessor for the 7590 the [7500](https://github.com/jamieernest/Dell-Inspiron-7501-Hackintosh) so Thank you very much! By the way does sleep fully work in your build and does trackpad gestures work?

**Comment by tctien342** [comment]
@jamieernest both sleep and trackpad work very well in mine laptop, u can contact me at telegram `@SaintNobita`
