### ISSUE TITLE
Bug when using with MacsFanControl to change fan speed

### ISSUE THREAD

**Issue by tctien342** [tctien342/Dell-Inspiron-7591-Hackintosh#64]
@lvs1974, I found that using MacsFanControl to change fan speed base on sensor temperature will cause laptop become unstable!
+ Cant control brighness anymore (F6 and F7)
+ Battery not update AC status when plugin (very slow, take about 1min to change the icons)
+ Wifi unstable

p/s: I think MacsFanControl try to send many command into EC so it break it! Maybe we should have add some action threshold into DellSMC kext!

**Comment by lvs1974** [comment]
@tctien342: it is known behaviour when fan control is overridden.
The same happens in Windows (F6 and F7 stop working definitely).

PS: Fn+S and Fn+B still works.

**Comment by tctien342** [comment]
@lvs1974 , thanks you for this info. Hope dell will fix this some day.

**Comment by yanwuu** [comment]
In the same situation, if the type-c interface is used for power supply and Macs fan control is used, the power status will never be updated unless the computer is restarted.
