### ISSUE TITLE
Suggest to add smbios 16.4，USB port customization: UsbConnector: 9

### ISSUE THREAD

**Issue by yanwuu** [tctien342/Dell-Inspiron-7591-Hackintosh#65]
1.I think the 16.4 native cpu is i7-9750, which is more suitable for this computer
2.USB port customization: don’t choose internal for interface type; 255, don’t choose USB3; 3
I have encountered that after customizing the USB, the two USB ports and the mobile hard disk are built-in; and the type-C interface displays normally.
So choose these two USB ports as TYPEC: UsbConnector: 9
![image](https://user-images.githubusercontent.com/17713852/97583362-d38ec180-1a31-11eb-9000-bd31b6a98ba8.png)

**Comment by yanwuu** [comment]
@tctien342

**Comment by tctien342** [comment]
> @tctien342 

Okay, i'll use 16,4 in next build and testing usb port, pls share your usbports.kext

**Comment by yanwuu** [comment]
> > @tctien342
> 
> Okay, i'll use 16,4 in next build and testing usb port, pls share your usbports.kext

[USBPorts.kext.zip](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/files/5462152/USBPorts.kext.zip)

**Comment by jamieernest** [comment]
This might not be related but for some reason power management is worse on my [Inspiron 7501](https://github.com/jamieernest/Dell-Inspiron-7501-Hackintosh) (i7-10750H)with macbookpro16,4 and my cpu is above 10W almost all the time
