### ISSUE TITLE
dw1560 support

### ISSUE THREAD

**Issue by OysterQAQ** [tctien342/Dell-Inspiron-7591-Hackintosh#67]
latest efi do not support dw1560 wifi card

**Comment by tctien342** [comment]
Current built add only `AirPort_BrcmNIC` in kernel for my DW1820A and it work perfectly @@, maybe you can try add `AirPort_Brcm4360` to kexts in config.plist and see if it work

**Comment by OysterQAQ** [comment]
thank you ,dw1560 is working after disable AirPort_BrcmNIC in kernel
