### ISSUE TITLE
Occasionally stuck loading with 060221 build (almost perfect with 0.63beta)

### ISSUE THREAD

**Issue by RaymdZ** [tctien342/Dell-Inspiron-7591-Hackintosh#69]
I have been using the **beta-0.63 build** for months with Big Sur 11.2. **Everything went smooth, not even a single crash.** Thank you @tctien342 for your great contribution! 

The latest 060221 build seems quite strange to me. For around 50% chance, booting is not successful. Sorry that I don't know how to export the log file. So I upload a photo showing how it was stuck, for that 50% chance. "com.apple.AppleFSCompressionTypeZlib", every time. I am using a same model as your 7591, except for the intel card. Any ideas on the causes? 

![image](https://user-images.githubusercontent.com/17639715/114877684-1868b200-9e32-11eb-8957-d56897dda90d.png)

Speaking on the difference between beta-0.63 build, the modification of USBPort as proposed by @yanwuu did improve a bit, but not perfect. With beta-0.63 build, only 1 left USB port could recognize my external NVME drive. Now with 060221 build, all 3 USB ports can do. However, the type-c port couldn't recognize my external SSD, for both builds, unless I reboot with the drive connected. Hope it could be fixed also!

Lastly, for the HDMI hot plug issue... I am doing the "unplug-setting-display-detect monitor" routine every day lol. I wonder if that's possible to fix? If not, is it possible to have some (keyboard) shortcuts to finish that routine? 

If these are solved, I think I would be using your build for the rest of my 7591 laptop's life! XD
Thanks a lot!

**Comment by RaymdZ** [comment]
Update: 
Have replaced a BCM94360NG (equivalent to a 94360CS2) kext-free card. 
The problem exists regardless with build 060221, 180421, and 250421. It's safe only on beta-0.63 build.

**Comment by RaymdZ** [comment]
Update2:
I am glad to found out that the beta-0.63 build works almost perfectly with the replaced 94350NG card. 

1. AWDL is fully functional (of course).
2. Sleep-wake and even HIBERNATE cycle are so smooth. Hibernate for 12hr consumed only 1% battery. 
3. Power efficiency is quite good. Under normal web browsing and document work, I could shut down both fans by pressing Fn+T, and the cpu temperature remains around 40-50C, which is quite good for me.
4. Monitor detection for HDMI hot-plug could be done by keyboard shortcut automatically with little codes available [here](https://code.google.com/archive/p/detectdisplays/).
5. USB ports and thunderbolt work properly now (by setting thunderbolt mode in BIOS from "BIOS assist" to "Native" then back to "BIOS assist"...strange...).

Now, the beta-0.63 build looks perfect for me, except for the dead mic and dead gpu.

**Comment by lvs1974** [comment]
@RaymdZ: may I ask you how did you achieve a draining only 1% for 12hr?
I have Dell Inspiron 7590 with 56wh battery, and it looses 6-7% per 12 hr in a regular sleep (macOS BigSur 11.3).

**Comment by tctien342** [comment]
@RaymdZ U should try newest [build](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/releases/tag/build-0.6.8-v2)

**Comment by RaymdZ** [comment]
> @RaymdZ: may I ask you how did you achieve a draining only 1% for 12hr?
> I have Dell Inspiron 7590 with 56wh battery, and it looses 6-7% per 12 hr in a regular sleep (macOS BigSur 11.3).

I did not tune anything special other than using the EFI in this Repo.
I have the 97wh 7591 and BigSur 11.2. I did some testing these days. With thunderbolt enabled, it drains 10% battery for 6 hrs of regular sleep. That's much worse than your case. 
Normally I use the laptop with AC in the day, then unplug everything and get it hibernated at night. Either set hibernate mode to 25 or set a short standbydelay under hibernate mode 3. That gives me 99% the other day when I reopen the lid.

**Comment by RaymdZ** [comment]
> @RaymdZ U should try newest [build](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/releases/tag/build-0.6.8-v2)

Thanks for your reply. As said, I tried the latest builds one by one and the problem persisted. Sometimes, it also failed in booting and reboot automatically with some SMC related messages. But I am not familiar with that and cant figure out why. Maybe I should try a fresh install, but not in a near future...
 Anyway, I am pretty satisfied with the current setup, though it's the old build :)
