### ISSUE TITLE
Audio and Audio Jack not working

### ISSUE THREAD

**Issue by seyhadot** [tctien342/Dell-Inspiron-7591-Hackintosh#8]
how to fix audio and audio headset thank you

**Comment by tctien342** [comment]
Use applealc come with this repo and layout id = 13, install combojack fix too

**Comment by seyhadot** [comment]
Thank you it's working now but I have try to map Caplock to Ctrl but it's
not working do u know what to do?

**Comment by tctien342** [comment]
Humm... not try it! but if u want map command key to window key just go to System perfer -> keyboard -> modifier keys

**Comment by seyhadot** [comment]
Already try it but not working
